//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadioServer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60000")]
        public uint CONTROL_TCP_PORT {
            get {
                return ((uint)(this["CONTROL_TCP_PORT"]));
            }
            set {
                this["CONTROL_TCP_PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("keys.xml")]
        public string KEYS_FILE {
            get {
                return ((string)(this["KEYS_FILE"]));
            }
            set {
                this["KEYS_FILE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ldap_permissions.def")]
        public string LDAP_PERMISSION_DEF_FILE {
            get {
                return ((string)(this["LDAP_PERMISSION_DEF_FILE"]));
            }
            set {
                this["LDAP_PERMISSION_DEF_FILE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("audio")]
        public string FILE_STORE_ROOT {
            get {
                return ((string)(this["FILE_STORE_ROOT"]));
            }
            set {
                this["FILE_STORE_ROOT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("database.sqlite")]
        public string DB_FILE {
            get {
                return ((string)(this["DB_FILE"]));
            }
            set {
                this["DB_FILE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ldap")]
        public string LDAP_USERNAME {
            get {
                return ((string)(this["LDAP_USERNAME"]));
            }
            set {
                this["LDAP_USERNAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c7TGkkHyGJlsIqQavNa8Y-7ZgPeN_2dm")]
        public string LDAP_PASSWORD {
            get {
                return ((string)(this["LDAP_PASSWORD"]));
            }
            set {
                this["LDAP_PASSWORD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gymlit.cz")]
        public string LDAP_DOMAIN {
            get {
                return ((string)(this["LDAP_DOMAIN"]));
            }
            set {
                this["LDAP_DOMAIN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OU=Zaměstnanci,OU=Uživatelé,DC=gymlit,DC=cz")]
        public string LDAP_OU {
            get {
                return ((string)(this["LDAP_OU"]));
            }
            set {
                this["LDAP_OU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public uint SECURITY_CACHE_EXPIRATION {
            get {
                return ((uint)(this["SECURITY_CACHE_EXPIRATION"]));
            }
            set {
                this["SECURITY_CACHE_EXPIRATION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public uint SCHEDULER_CHECK_INTERVAL {
            get {
                return ((uint)(this["SCHEDULER_CHECK_INTERVAL"]));
            }
            set {
                this["SCHEDULER_CHECK_INTERVAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint PLAYBACK_DEV_OUT {
            get {
                return ((uint)(this["PLAYBACK_DEV_OUT"]));
            }
            set {
                this["PLAYBACK_DEV_OUT"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source={0};Version=3;PRAGMA foreign_keys = ON;")]
        public string SQLITE_CONN_STRING {
            get {
                return ((string)(this["SQLITE_CONN_STRING"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public uint SCHEDULER_PADDING_START {
            get {
                return ((uint)(this["SCHEDULER_PADDING_START"]));
            }
            set {
                this["SCHEDULER_PADDING_START"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public uint SCHEDULER_PADDING_END {
            get {
                return ((uint)(this["SCHEDULER_PADDING_END"]));
            }
            set {
                this["SCHEDULER_PADDING_END"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LOG_INFO {
            get {
                return ((bool)(this["LOG_INFO"]));
            }
            set {
                this["LOG_INFO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LOG_WARNING {
            get {
                return ((bool)(this["LOG_WARNING"]));
            }
            set {
                this["LOG_WARNING"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LOG_ERROR {
            get {
                return ((bool)(this["LOG_ERROR"]));
            }
            set {
                this["LOG_ERROR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("server.log")]
        public string LOG_FILE {
            get {
                return ((string)(this["LOG_FILE"]));
            }
            set {
                this["LOG_FILE"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Usage:\r\n\r\n-c or -console ... Run server in console mode (for debugging purposes)." +
            "\r\n\r\n-i or -install ... Installs Windows Service.\r\n\r\n-u or -uninstall ... Uninsta" +
            "lls Windows Service.\r\n")]
        public string PROGRAM_USAGE {
            get {
                return ((string)(this["PROGRAM_USAGE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Radio Server")]
        public string SERVICE_NAME {
            get {
                return ((string)(this["SERVICE_NAME"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Radio Server")]
        public string SERVICE_DISPLAYNAME {
            get {
                return ((string)(this["SERVICE_DISPLAYNAME"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("This service is school broadcast radio daemon. It recieves broadcast request from" +
            " the network and play them to school sound system.")]
        public string SERVICE_DESCRIPTION {
            get {
                return ((string)(this["SERVICE_DESCRIPTION"]));
            }
        }
    }
}
