//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RadioClient.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.7.32.9")]
        public string SERVER_IP {
            get {
                return ((string)(this["SERVER_IP"]));
            }
            set {
                this["SERVER_IP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60000")]
        public int CONTROL_TCP_PORT {
            get {
                return ((int)(this["CONTROL_TCP_PORT"]));
            }
            set {
                this["CONTROL_TCP_PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60001")]
        public int BROADCAST_PORT {
            get {
                return ((int)(this["BROADCAST_PORT"]));
            }
            set {
                this["BROADCAST_PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int RESPOND_TIMEOUT {
            get {
                return ((int)(this["RESPOND_TIMEOUT"]));
            }
            set {
                this["RESPOND_TIMEOUT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("trusted_hosts")]
        public string FINGERPRINT_STORE_FILE {
            get {
                return ((string)(this["FINGERPRINT_STORE_FILE"]));
            }
            set {
                this["FINGERPRINT_STORE_FILE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2048000")]
        public int TRANSFER_BUFFER_SIZE {
            get {
                return ((int)(this["TRANSFER_BUFFER_SIZE"]));
            }
            set {
                this["TRANSFER_BUFFER_SIZE"] = value;
            }
        }
    }
}
